In [1]:
import numpy as np
from math import inf  
n = 5
m = 15
w = [12, 2, 1 , 1, 4]
v = [10, 2, 1, 2, 5]

In [2]:
# class DNA:
    # def __init__(self): #không điền gì vô, muốn nó random thì khỏi khai vô đây 
        # self.dvar = np.random.randint(0,2,n) #tạo array 0,1 có độ dài n 
        # self.fitness = np.sum(self.dvar*v) #fitness là khả năng sinh sôi ở thế hệ kế tiếp, bài max thì fitness càng cao càng tốt, min ngược lại 
        # total_weight = np.sum(self.dvar*w)
        # err = total_weight - m
        # self.fitness = self.fitness - max(2*err,0) #chỉ trừ khi err lớn hơn 0, số 2 mình tự điều chỉnh 

In [3]:
class DNA: #khúc này là khai báo thui chứ chưa chạy, chừng nào mình gọi mới chạy, DNA chứa decision var 
    def __init__(self): #bắt buộc phải có cái initial "init" này, các hàm dưới tự đặt tên 
        self.dvar = np.random.randint(0,2,n)  
        self.fitness = None #kiểu dữ liệu non là không có gì ở trỏng hết  
        #không muốn cái hàm initial chạy nhiều lần nên sẽ tách ra như vậy chứ không viết như ở trên 
    def calc_fitness(self):
        self.fitness = np.sum(self.dvar*v)
        total_weight = np.sum(self.dvar*w)
        err = total_weight - m
        if total_weight > m: #lố constrain
            self.fitness = self.fitness - 2*err #số 2 tâm linh của anh Lộc (bài khác tự tâm linh)
            #cho bằng 0 thì nó cũng chạy được nma nếu bỏ thì uổng nên chỉ phạt thui 
    def mutate(haha): #mutate là thêm gen lạ vào quần thể #haha hay tên gì cũng được, quan trọng là đồng nhất với hàm ở dưới
        for i in range(n):
            if np.random.rand()<0.25: #0.25 là mutation rate, lại là 1 con số tâm linh 
                haha.dvar[i] = 1 - haha.dvar[i] #randome đổi kh thành 1, decision var là binary

In [4]:
dna = DNA() #khúc này là gọi nó ra nó mới chạy nè 
print(dna.dvar)
print(dna.fitness) #fitness là tổng var, sẽ trừ fitness dựa vào mức độ sai chứ kh trừ số cố định 

[1 1 0 1 1]
None


In [5]:
dna.calc_fitness() #phải calc thì print mới ra
print(dna.fitness) 

11


In [6]:
def crossover(dna1,dna2): #khúc này cũng là khai báo, khai báo trước để lát hồi đưa vô vòng lặp chính 
    new_dna = DNA()
    mid = np.random.randint(0,n)
    a1 = dna1.dvar[0:mid]
    a2 = dna2.dvar[mid:n]
    new_dna.dvar = np.concatenate([a1,a2])
    new_dna.calc_fitness()
    return new_dna #trao đổi chéo để tạo ra được 1 array tốt hơn 
#cần có return vì hàm hày cần trả về 1 giá trị mới, còn những hàm và tự thay đổi ở trong chuỗi thôi thì kh cần

In [7]:
d4 = DNA()
print(d4.dvar)

[0 0 1 1 1]


In [8]:
d4.mutate()
print(d4.dvar)

[0 0 1 0 1]


In [9]:
d1 = DNA()
print(d1.dvar)
d2 = DNA()
print(d2.dvar)

[0 0 0 1 0]
[0 1 1 0 0]


In [10]:
d3 = crossover(d1, d2)
print(d3.dvar)
print(d3.fitness)

[0 1 1 0 0]
3


In [11]:
# initialize first population
#khúc này mới bắt đầu vòng lặp chính, ở trên là khai báo 
#câu lệnh dưới đây là để append cái quần thể ban đầu vô population, là chuỗi gồm nhiều DNA random  
pop_size = 5
population = [] #trong population chứa nhiều cái dna, số dna pop_size, trong dna chứa dvar và fitness
for i in range(pop_size):
    population.append(DNA()) #dna ban đầu mình khai 2 cái dna và fitness
    population[i].calc_fitness()
    print(population[i].fitness)

7
13
10
11
0


In [12]:
#hàm linear không tốt bằng hàm curve vì mình muốn là càng tốt càng nhiều 
def curve(x):
    return int(x*x/8)

In [13]:
#bước natural selection --> linh hồn của GA 
#pool mating là chứa các DNA, nếu thằng nào tốt thì bỏ vô pool nhiều
#idea là mình sẽ là: 
#1 có 3 số, 2 có 5 số, 3 có 1 số, 4 có 0 số 
#khi bỏ vô sẽ bỏ kiểu 3 số 1, 5 số 2 and so on --> thằng nào tốt bỏ vô nhiều thì xác suất lần sau bốc dc tốt nhiều hơn 
pool = []
for i in range(pop_size):
    for j in range(curve(population[i].fitness)): #nó sẽ chạy từ 0 tới số lượng của fitness --> mỗi lần chạy bỏ 1 số vô --> fit = bnhiu thì bỏ bnhiu số 
        pool.append(i)

print(pool) #những thằng tốt thì id nó sẽ xuất hiện nhiều trong pool
#pool là tập các số thứ tự của các chuỗi mình đã tạo ra ở cái population ban đầu, thằng nào tốt xuất hiện nhiều để xác suất bốc trúng cao hơn 

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [14]:
id = np.random.choice(pool)
print(id) #bốc 1 thằng trong cái pool ra 

1


In [15]:
id1 = np.random.choice(pool)
id2 = np.random.choice(pool)
print(population[id1].dvar) #lấy thằng có số thứ tự là id1 trong population
print(population[id2].dvar)

dna3 = crossover(population[id1], population[id2])
print(dna3.dvar)


[1 1 1 0 0]
[1 1 1 0 0]
[1 1 1 0 0]


In [16]:
#vòng lặp chíng của GA
best_dna= DNA()
best_fitness= - inf
num_of_iteration=10
for it in range(num_of_iteration):
    print("iteration: ", it)
    print("best fitness is", best_fitness)
    #selection
    pool=[]
    for i in range(pop_size): # run from 0-> pop_size -1
        for j in range(max(population[i].fitness,0)):
            pool.append(i)
    #crossover
    new_population=[]
    for i in range(pop_size):
        id1 = np.random.choice(pool)
        id2 = np.random.choice(pool)
        new_dna= crossover(population[id1], population[id2]) #không chấm dvar vì ở trên có rùi 
        #mutation
        new_dna.mutate()
    #calculate population fitness
        new_dna.calc_fitness()
    #update 
        if new_dna.fitness> best_fitness:
            best_fitness = new_dna.fitness
            best_dna=new_dna
        new_population.append(new_dna)
    population = new_population

iteration:  0
best fitness is -inf
iteration:  1
best fitness is 13
iteration:  2
best fitness is 13
iteration:  3
best fitness is 13
iteration:  4
best fitness is 13
iteration:  5
best fitness is 13
iteration:  6
best fitness is 13
iteration:  7
best fitness is 13
iteration:  8
best fitness is 13
iteration:  9
best fitness is 13


In [17]:
print(best_dna.dvar)

[1 1 1 0 0]
